name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Order.sln

      - name: Build
        run: dotnet build Order.sln --no-restore -c Release

      - name: Test
        run: dotnet test Order.sln --no-build -c Release --verbosity normal

  bicep-validate:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if any Bicep files exist
        id: bicepcheck
        run: |
          if find . -name "*.bicep" | grep -q .; then
            echo "has_bicep=true" >> $GITHUB_OUTPUT
          else
            echo "has_bicep=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Azure CLI
        if: ${{ steps.bicepcheck.outputs.has_bicep == 'true' }}
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az version
            az bicep version
            find . -name "*.bicep" -print -exec az bicep build --file {} \;

